### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by xoolive** [cathaypacific8747/fr24#19]
I don't have time to dig much more into this right now, so let me document it here first before I forget. I currently have some authentication issues (context: trying to port my code from the older version to the newer API, and struggling to find where I could just get the JSON before the pyarrow...)

More generally, it would be nice to have an extra option as I could prefer to run anonymously by default, and login only when necessary:

```python
async with FR24(login: bool | {'username': user, 'password': pass}) as fr24:
    ...
```

Currently, on my side, authentication in the asynccontextmanager fails with 
```
ConnectError: All connection attempts failed
```

Surprisingly, in the TUI part of the code, I just use the following (without the FR24 client) and it still works:

```python
self.auth = await login(self.client)
```

**Comment by cathaypacific8747** [comment]
I am unable to reproduce the ConnectError on my end, but I suspect the issue is due to the custom `httpx.AsyncHTTPTransport(retries=5)` passed into the `httpx.AsyncClient` [here](https://github.com/cathaypacific8747/fr24/blob/ed822d9a65285c2c4047a9b4d354c38d70eb25b6/src/fr24/base.py#L26). The [documentation for the retry logic](https://www.python-httpx.org/advanced/transports/#http-transport) is rather lacking, so there might be something I'm overlooking. Does removing it resolve the issue?

As for how to get the JSON before pyarrow, you could do this:
```py
from fr24.core import FR24

async def my_playback() -> None:
    async with FR24() as fr24:
        pb = fr24.playback(flight_id=0x2FB3041)
        response = await pb.api.fetch() # raw json here
        pb.data.add_api_response(json_response) # transformed to arrow table

await my_playback()
```

I'll have a go at the proposed anonymous-by-default implementation :)

**Comment by cathaypacific8747** [comment]
Just implemented the authentication override:
```py
# reads from environment variables/config file by default
async with FR24() as fr24:
    ...
# force anonymous
async with FR24(creds=None) as fr24:
    ...
async with FR24(creds={"username": "...", "password": "..."}) as fr24:
    ...
async with FR24(creds={"subscriptionKey": "...", "token": "..."}) as fr24:
    ...
```

**Comment by xoolive** [comment]
Actually, more general architecture concern: how to proceed if I want to come with my own httpx.AsyncClient because I want to share it with other tools?

**Comment by cathaypacific8747** [comment]
I had been using `AsyncHTTPTransport(retries=5)` because I was intermittently receiving connection errors particularly during livefeed requests: it wasn't really necessary. I had a quick glance at the [default `AsyncHTTPTransport`](https://github.com/encode/httpx/blob/4b85e6c3898b94e686b427afd83138c87520b479/httpx/_client.py#L1474) created by the `httpx.AsyncClient` but was unable to find any differences with our custom one.

Anyways, I've made a commit that allows you to pass a custom client and made the login explicit:
```py
client = httpx.AsyncClient(transport=httpx.AsyncHTTPTransport(retries=5))
async with FR24(client) as fr24:
    # anonymous by default
    await self.http.login() # reads from environment or configuration file, or,
    await self.http.login(creds={"username": "...", "password": "..."}) # or,
    await self.http.login(creds={"subscriptionKey": "...", "token": "..."})
```
This is a breaking change for my codebase as it no longer autologins, but yeah, explicit logins do look nicer.
